git:
  name: git
  command: git
  scanner: qualified_simple
subversion: &subversion
  name: Subversion
  command: svn
  scanner: subversion
svn: *subversion
vagrant:
  name: Vagrant
  cmoonad: vagrant
  scanner: qualified_simple
cvs:
  name: Concurrent Versions System
  command: cvs
  scanner: first_line_simple
