git:
  name: git
  command: git
  scanner: simple_with_prefix
svn: &svn
  name: Subversion
  command: svn
  scanner: subversion
subversion: *svn
vagrant:
  name: Vagrant
  cmoonad: vagrant
  scanner: simple_with_prefix
