git:
  name: git
  command: git
  scanner: qualified_simple
subversion: &subversion
  name: Subversion
  command: svn
  scanner: subversion
svn: *subversion
cvs:
  name: Concurrent Versions System
  command: cvs
  scanner: first_line_simple
mercurial: &mercurial
  name: Mercurial
  command: hg
  scanner: first_line_simple
hg: *mercurial
darcs:
  name: Darcs
  command: darcs
  scanner: darcs
bazaar: &bazaar
  name: Bazaar
  command: bzr
  scanner: bazaar
bzr: *bazaar
vagrant:
  name: Vagrant
  cmoonad: vagrant
  scanner: qualified_simple
