bazaar: &bazaar
  name: Bazaar
  command: bzr
  scanner: bazaar
bzr: *bazaar
cvs:
  name: Concurrent Versions System
  command: cvs
  scanner: first_line_simple
darcs:
  name: Darcs
  command: darcs
  scanner: darcs
git:
  name: git
  command: git
  scanner: qualified_simple
homebrew: &homebrew
  name: Homebrew
  command: brew
  scanner: simple
brew: *homebrew
java: &java
  name: Java
  command: java
  option: -version
  scanner: java
javac:
  <<: *java
  command: javac
mercurial: &mercurial
  name: Mercurial
  command: hg
  scanner: first_line_simple
hg: *mercurial
perl:
  name: perl
  command: perl
  scanner: perl
subversion: &subversion
  name: Subversion
  command: svn
  scanner: subversion
svn: *subversion
vagrant:
  name: Vagrant
  cmoonad: vagrant
  scanner: qualified_simple
